"""Feature definitions: one entity (user), one feature view sourced from
the parquet file generated by src/generate_data.py, with a 90-day TTL —
same 'user' entity theme as project 08's recommender, now as reusable,
versioned, centrally-defined features instead of ad-hoc DataFrame columns
computed inline wherever they're needed.
"""

from datetime import timedelta
from feast import Entity, FeatureView, Field, FileSource
from feast.types import Float32, Int64

user = Entity(name="user_id", join_keys=["user_id"])

user_features_source = FileSource(
    path="data/user_features.parquet",
    timestamp_field="event_timestamp",
    created_timestamp_column="created_timestamp",
)

user_features_view = FeatureView(
    name="user_features",
    entities=[user],
    ttl=timedelta(days=90),
    schema=[
        Field(name="avg_rating_given", dtype=Float32),
        Field(name="num_ratings", dtype=Int64),
        Field(name="account_age_days", dtype=Int64),
    ],
    source=user_features_source,
)
